image: maven:3-jdk-11

stages:
  - build
  - test
  

build-java-project:
  cache:
    paths:
      - .m2/repository/
      - target/
  
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - ./target/*.jar
      - java -jar C:\Users\Dell\Downloads\md-pipeline-demo\md\target\md-0.0.1-SNAPSHOT.jar

test-java-project:
  stage: test
  script:
    - mvn test

   

