variables:
  ACCESS_KEY: $AWS_ACCESS_KEY_ID
  SECRET_KEY: $AWS_SECRET_ACCESS_KEY
  BUCKET_NAME: $AWS_S3
  BUCKET_REGION: $AWS_DEFAULT_REGION

stages:
  - build

build:
  stage: build
  image: antora/antora:latest
  script:
    - antora antora-playbook.yml --fetch
    
  artifacts:
    paths:
      - ./public

deploy_to_s3:
  before_script:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_S3: $AWS_S3
    #BUCKET_REGION: $AWS_DEFAULT_REGION
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    #- aws configure set default.region $AWS_S3
    - aws s3 cp ./public s3://manuv2u/ --region ap-south-1 --only-show-errors
