variables:
  S3_ACCESS_KEY: $AWS_ACCESS_KEY_ID
  S3_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET_NAME: $AWS_S3

before_script:
  - apt-get update
  - apt-get -y install awscli
  - aws configure set aws_access_key_id $S3_ACCESS_KEY
  - aws configure set aws_secret_access_key $S3_SECRET_KEY

stages:
  - build

build:
  stage: build
  image: antora/antora:latest
  script:
    - antora --pull --fetch antora-playbook.yml --fetch
    
  artifacts:
    paths:
      - ./public

deploy_to_s3:
  stage: build
  image: amazon/aws-cli
  script:
    - aws s3 cp ./public s3://$S3_BUCKET_NAME/

