variables:
  S3_ACCESS_KEY: $AWS_ACCESS_KEY_ID
  S3_SECRET_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET_NAME: $AWS_S3


stages:
  - build

build:
  stage: build
  image: antora/antora:latest
  script:
    - antora antora-playbook.yml --fetch
    
  artifacts:
    paths:
      - ./public

deploy_to_s3:
  stage: build
  image: amazon/aws-cli:2.x
  variables:
    AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: $S3_SECRET_KEY
  script:
    - aws s3 cp ./public s3://$S3_BUCKET_NAME/

