variables:
  ACCESS_KEY: $AWS_ACCESS_KEY_ID
  SECRET_KEY: $AWS_SECRET_ACCESS_KEY
  BUCKET_NAME: $AWS_S3
  BUCKET_REGION: $AWS_DEFAULT_REGION

stages:
  - build

build:
  stage: build
  image: antora/antora:latest
  script:
    - antora antora-playbook.yml --fetch
    
  artifacts:
    paths:
      - ./public

deploy_to_s3:
  stage: build
  image: amazon/aws-cli:2.x
  variables:
    ACCESS_KEY: $AWS_ACCESS_KEY_ID
    SECRET_KEY: $AWS_SECRET_ACCESS_KEY
    BUCKET_NAME: $AWS_S3
    BUCKET_REGION: $AWS_DEFAULT_REGION
  script:
    - aws configure set aws_access_key_id $ACCESS_KEY
    - aws configure set aws_secret_access_key $SECRET_KEY
    - aws s3 cp ./public s3://$BUCKET_NAME/ --region $BUCKET_REGION --only-show-errors
