variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3-jdk-11

stages:
  - build
  - test


include:
  - template: Code-Quality.gitlab-ci.yml


build-java-project:
  cache:
    paths:
      - .m2/repository/
      - target/
  
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - ./target/*.jar

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]



