image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy

build-java-project:
  cache:
    paths:
      - .m2/repository/
      - target/
  
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - ./target/*.jar 

test-java-project:
  stage: test
  script:
    - mvn test

deploy-java-project:
  stage: deploy
  script:
    - java -jar C:\Users\Dell\Downloads\md-pipeline-demo\md\target\md-0.0.1-SNAPSHOT.jar
    - curl "https://localhost:7070/"    
  

